[supervisord]
nodaemon=true
user=root

[program:dump1090]
command=/usr/local/bin/dump1090 --net --net-bind-address localhost --net-sbs-port 30003
autostart=true
autorestart=true
startretries=0
exitcodes=0
startsecs=1
stderr_logfile=/var/log/dump1090.err.log
stdout_logfile=/var/log/dump1090.out.log

[program:node]
command=/usr/local/bin/node /app/tcp-to-websocket.cjs
autostart=true
autorestart=true
startretries=0
exitcodes=0
startsecs=1
stderr_logfile=/var/log/node.err.log
stdout_logfile=/var/log/node.out.log

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
autostart=true
autorestart=true
startretries=0
exitcodes=0
startsecs=1
stderr_logfile=/var/log/nginx.err.log
stdout_logfile=/var/log/nginx.out.log
